name: delete-tag

# mannual run
on:
    workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - uses: rafalkk/remove-dockertag-action@v1
        with:
          tag_name: main
          github_token: ${{ secrets.GITHUB_TOKEN }}